oauth2:
  user:
    kakao:
      client-id: 0320ef81c92e35eb95e38e18be1bba48
      client-secret: Y2bpWERVMoJFoybA3qWXjmXCivQm4uxT
      redirect-uri: http://localhost:8080/redirect/oauth
#    naver:
#      client-id: sCfhQHgPVQFFf8RTGjVe
#      client-secret: 비밀키
#      redirect-uri: http://localhost:8080/redirect/oauth
  provider:
    kakao:
      token-uri: https://kauth.kakao.com/oauth/token
      user-info-uri: https://kapi.kakao.com/v2/user/me
#    naver:
#      token-uri: https://nid.naver.com/oauth2.0/token
#      user-info-uri: https://openapi.naver.com/v1/nid/me


jwt:
  token:
    secret-key: secret-key
  access-token:
    expire-length: 1800000
  refresh-token:
    expire-length: 1209600000