cloud:
  aws:
    credentials:
      access-key: AKIAWU5EDN7YUESCT5O4
      secret-key: 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
    s3:
      bucket: catcha
    region:
      static: ap-northeast-2
    stack:
      auto: false

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://catcher.ccnmfvd4t0d1.ap-northeast-2.rds.amazonaws.com:3306/catcher?characterEncoding=UTF-8&serverTimezone=UTC
    username: catcher
    password: catchercatcher
  profiles:
    include: oauth

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
logging:
  level:
    org.hibernate:
      SQL: DEBUG